#![deny(future_incompatible, let_underscore, nonstandard_style, clippy::all)]
#![warn(clippy::pedantic, clippy::nursery)]

use proc_macro::TokenStream;
use proc_macro_error::{abort, proc_macro_error};
use quote::quote;
use syn::{Data, DataStruct, Expr, LitStr, Type, TypePath, parse_macro_input, spanned::Spanned};

/// Derives an implementation of `codegen::types::structure::StructFields`.
///
/// The benefit of using `#[derive(StructFields)]` is that all index- or order-dependent logic required by
/// `impl StructFields` is automatically generated by this implementation, including the field index as required by
/// `StructField::new` and the fields as returned by `StructFields::to_vec`.
///
/// # Prerequisites
///
/// In order to derive from [`StructFields`], you must implement (or derive) [`Eq`] and [`Copy`] as required by
/// `StructFields`.
///
/// Moreover, `#[derive(StructFields)]` can only be used for `struct`s with named fields, and may only contain fields
/// with either `StructField` or [`PhantomData`] types.
///
/// # Attributes for [`StructFields`]
///
/// Each `StructField` field must be declared with the `#[value_type(...)]` attribute. The argument of `value_type`
/// must be a field or method call on `ModuleContext` that gives a `BasicTypeEnum`.
///
/// # Example
///
/// The following is an example of an LLVM slice implemented using `#[derive(StructFields)]`.
///
/// ```rust,ignore
/// use nac3core::{
///     codegen::types::structure::StructField,
///     inkwell::values::{IntValue, PointerValue},
/// };
/// use nac3core_derive::StructFields;
///
/// // All classes that implement StructFields must also implement Eq and Copy
/// #[derive(PartialEq, Eq, Clone, Copy, StructFields)]
/// pub struct SliceValue<'ctx> {
///     // Declares ptr have a value type of a pointer
///     #[value_type(ptr)]
///     ptr: StructField<'ctx, PointerValue<'ctx>>,
///
///     // Declares len have a value type of size_t, which depends on the target compilation platform
///     #[value_type(size_t)]
///     len: StructField<'ctx, IntValue<'ctx>>,
/// }
/// ```
#[proc_macro_derive(StructFields, attributes(value_type))]
#[proc_macro_error]
pub fn derive_struct_fields(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as syn::DeriveInput);
    let ident = &input.ident;

    let Data::Struct(DataStruct { fields, .. }) = &input.data else {
        abort!(input, "Only structs with named fields are supported");
    };
    // Check if struct<'ctx>
    if input.generics.params.len() != 1 {
        abort!(input.generics, "Expected exactly 1 generic parameter")
    }

    let mut phantom_info = Vec::new();
    let mut field_info = Vec::new();

    for field in fields {
        let Some(name) = &field.ident else {
            abort!(field, "Only structs with named fields are supported");
        };

        if let Type::Path(TypePath { qself: None, path, .. }) = &field.ty
            && path.segments.len() == 1
        {
            let segment = &path.segments[0];
            if segment.ident == "PhantomData" {
                phantom_info.push(name);
                continue;
            } else if segment.ident == "StructField" {
                let Some(value_type_attr) =
                    field.attrs.iter().find(|attr| attr.path().is_ident("value_type"))
                else {
                    abort!(field, "Expected #[value_type(...)] attribute for field");
                };

                let Ok(value_type_expr) = value_type_attr.parse_args::<Expr>() else {
                    abort!(value_type_attr, "Expected expression in #[value_type(...)]");
                };

                field_info.push((name, quote! { ctx.#value_type_expr }));
                continue;
            }
        }

        abort!(field, "Only StructField and PhantomData are allowed");
    }

    let phantoms_create = phantom_info.iter().map(|id| quote! { #id: ::std::marker::PhantomData });

    let field_values = field_info.iter().map(|(_, value_expr)| value_expr);
    let field_names = field_info.iter().map(|(id, _)| id);
    let field_names2 = field_names.clone();

    let create = quote! { ::nac3core::codegen::types::structure::StructField::create_at };
    let advance = quote! {{ let tmp = counter; counter += 1; tmp }};
    let fields_create = field_names.clone().map(|id| {
        let id_lit = LitStr::new(&id.to_string(), id.span());
        quote! { #id: #create(#advance, #id_lit, #id) }
    });

    let impl_block = quote! {
        #[automatically_derived]
        impl<'ctx> #ident<'ctx> {
            #[allow(too_many_arguments)]
            pub fn from_types(#(#field_names: ::nac3core::inkwell::types::BasicTypeEnum<'ctx>,)*) -> Self {
                let mut counter = 0u32;
                Self { #(#fields_create,)* #(#phantoms_create,)* }
            }
        }
        #[automatically_derived]
        impl<'ctx> ::nac3core::codegen::types::structure::StructFields<'ctx> for #ident<'ctx> {
            fn new(ctx: &::nac3core::codegen::ModuleContext<'ctx>) -> Self {
                Self::from_types(#(#field_values.into(),)*)
            }

            fn to_vec(&self) -> ::std::vec::Vec<(&'static str, ::nac3core::inkwell::types::BasicTypeEnum<'ctx>)> {
                vec![#(self.#field_names2.into(),)*]
            }
        }
    };

    impl_block.into()
}

/// Derives an implementation of `codegen::types::ProxyType`. You must specify either one
/// of `#[llvm_ty(...)]` or `#[llvm_ref(...)]` attributes.
///
/// ## Pass by value
///
/// Use `#[llvm_ty(Value, ty)]` to indicate that the type is passed around by value.
/// `Value` is the Inkwell wrapper type over this kind of value (e.g., `StructValue`, `IntValue`, etc.), and
/// `ty` is the LLVM type representing how this type is passed around.
///
/// You are provided with `self` and `ctx: &ModuleContext<'ctx>` to evaluate `ty`.
///
/// ## Pass by reference
///
/// Use `#[llvm_ref(ty)]` to indicate that the type is passed around by reference (i.e. `PointerValue`).
/// The type accessed indirectly through this pointer is `ty`.
///
/// You are provided with `self` and `ctx: &mut CodeGenContext<'ctx, '_>` to evaluate `ty`.
///
/// # Example
///
/// ```rust,ignore
/// // Declare a struct.
/// #[derive(Clone, Copy, StructFields)]
/// pub struct MyStruct<'ctx> {
///     #[value_type(size_t)]
///     pub foo: StructField<'ctx, IntValue<'ctx>>,
///     #[value_type(size_t)]
///     pub bar: StructField<'ctx, IntValue<'ctx>>,
/// }
///
/// // Wrapper for passing this struct by value.
/// #[derive(Clone, Copy, ProxyType)]
/// #[llvm_ty(StructValue<'ctx>, self.inner.llvm_ty)]
/// pub struct DirectType<'ctx> {
///     pub(crate) inner: BuiltinStruct<'ctx, StringStructFields<'ctx>>,
/// }
///
/// // Wrapper for passing this struct by pointer.
/// #[derive(Clone, Copy, ProxyType)]
/// #[llvm_ref(self.inner.llvm_ty)]
/// pub struct IndirectType<'ctx> {
///     pub(crate) inner: BuiltinStruct<'ctx, StringStructFields<'ctx>>,
/// }
/// ```
#[proc_macro_derive(ProxyType, attributes(llvm_ty, llvm_ref))]
#[proc_macro_error]
pub fn derive_type(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as syn::DeriveInput);
    let name = &input.ident;

    // Insert a 'ctx lifetime to the impl if not present
    let mut generics = input.generics.clone();
    if !generics.lifetimes().any(|lt| lt.lifetime.ident == "ctx") {
        generics.params.insert(0, syn::parse_quote!('ctx));
    }
    let impl_generics = generics.split_for_impl().0;
    let (_, ty_generics, where_clause) = input.generics.split_for_impl();

    // Find either the #[llvm_ty(...)] or #[llvm_ref(...)] attribute
    let mut derive_info = None;
    for attr in &input.attrs {
        if attr.path().get_ident().is_some_and(|x| x == "llvm_ty" || x == "llvm_ref") {
            if derive_info.is_some() {
                abort!(attr, "Multiple llvm_ty/llvm_ref attributes found");
            }
            derive_info = Some(&attr.meta);
        }
    }
    let Some(derive_info) = derive_info else {
        abort!(input, "Expected either #[llvm_ty(...)] or #[llvm_ref(...)]");
    };

    // Let the macro_rules! macro do the actual implementation.
    //
    // This avoids having to parse the attribute arguments, which is complicated
    // compared to macro_rules! matching.
    quote! {
        ::nac3core::codegen::types::impl_proxy_type! {
            [#impl_generics] [#name #ty_generics #where_clause]
            |self, ctx| #derive_info
        }
    }
    .into()
}
