[package]
name = "nac3parser"
version = "0.1.2"
description = "Parser for python code."
authors = [ "RustPython Team", "M-Labs" ]
build = "build.rs"
license = "MIT"
edition = "2024"

[build-dependencies]
lalrpop = "0.23"

[dependencies]
nac3ast = { path = "../nac3ast" }
lalrpop-util = "0.23"
log = "0.4"
unic-emoji-char = "0.9"
unic-ucd-ident  = "0.9"
unicode_names2 = "2.0"
phf = { version = "0.13", features = ["macros"] }
ahash = "0.8"

[dev-dependencies]
insta = "1.44"
