[package]
name = "nac3artiq"
version = "0.1.0"
authors = ["M-Labs"]
edition = "2021"

[lib]
name = "nac3artiq"
crate-type = ["cdylib"]

[dependencies]
itertools = "0.12"
pyo3 = { version = "0.20", features = ["extension-module"] }
parking_lot = "0.12"
tempfile = "3.8"
nac3parser = { path = "../nac3parser" }
nac3core = { path = "../nac3core" }
nac3ld = { path = "../nac3ld" }

[dependencies.inkwell]
version = "0.2"
default-features = false
features = ["llvm14-0", "target-x86", "target-arm", "target-riscv", "no-libffi-linking"]

[features]
init-llvm-profile = []
