[package]
name = "nac3artiq"
version = "0.1.0"
authors = ["M-Labs"]
edition = "2024"

[lib]
name = "nac3artiq"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
indexmap = "2.14"
itertools = "0.14"
pyo3 = { version = "0.28", features = ["extension-module"] }
parking_lot = "0.12"
tempfile = "3.27"
nac3core = { path = "../nac3core" }
nac3binutils = { path = "../nac3binutils" }

[features]
init-llvm-profile = []
escape-analysis = ["nac3core/escape-analysis"]
malloc = ["nac3core/malloc"]
