[package]
name = "nac3ast"
version = "0.1.0"
authors = ["RustPython Team", "M-Labs"]
edition = "2024"

[features]
default = ["constant-optimization", "fold"]
constant-optimization = ["fold"]
fold = []

[dependencies]
parking_lot = "0.12"
string-interner = "0.20"
fxhash = "0.2"

[lints]
workspace = true
