[package]
name = "nac3core"
version = "0.1.0"
authors = ["M-Labs"]
edition = "2024"

[features]
default = ["derive", "ctrc"]
ctrc = ["malloc"]
derive = ["dep:nac3core_derive"]
escape-analysis = []
malloc = []

[dependencies]
anyhow = "1.0"
itertools = "0.15"
crossbeam = "0.8"
indexmap = "2.14"
parking_lot = "0.12"
nac3core_derive = { path = "nac3core_derive", optional = true }
nac3parser = { path = "../nac3parser" }
strum = "0.28"
strum_macros = "0.28"

# TODO: revert back to the crates.io version once https://github.com/TheDan64/inkwell/pull/683
# is included in the latest release.
[dependencies.inkwell]
git = "https://github.com/TheDan64/inkwell"
rev = "317feaf109d990271b5194d7b414dee98628bd95"
default-features = false
features = ["llvm22-1-prefer-dynamic", "target-x86", "target-arm", "target-riscv", "no-libffi-linking"]

[dev-dependencies]
test-case = "3.3"
indoc = "2.0"
insta = "1.47"
function_name = "0.3"

[build-dependencies]
build-rs = "0.3"
regex = "1.12"

[lints]
workspace = true
