[package]
name = "nac3core"
version = "0.1.0"
authors = ["M-Labs"]
edition = "2021"

[features]
default = ["derive"]
derive = ["dep:nac3core_derive"]
no-escape-analysis = []

[dependencies]
itertools = "0.14"
crossbeam = "0.8"
indexmap = "2.7"
parking_lot = "0.12"
nac3core_derive = { path = "nac3core_derive", optional = true }
nac3parser = { path = "../nac3parser" }
strum = "0.27"
strum_macros = "0.27"

[dependencies.inkwell]
version = "0.5"
default-features = false
features = ["llvm16-0-prefer-dynamic", "target-x86", "target-arm", "target-riscv", "no-libffi-linking"]

[dev-dependencies]
test-case = "3.3"
indoc = "2.0"
insta = "1.42"
function_name = "0.3"

[build-dependencies]
regex = "1.11"
