[package]
name = "nac3standalone"
version = "0.1.0"
authors = ["M-Labs"]
edition = "2024"

[features]
default = ["escape-analysis", "malloc"]
escape-analysis = ["nac3core/escape-analysis"]
malloc = ["nac3core/malloc"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
parking_lot = "0.12"
nac3core = { path = "../nac3core" }
